'use strict';
// Trainingsplan-Daten: Handball-Athletik für zuhause (2× pro Woche).
//
// target.kind: 'reps' (Wiederholungen) oder 'time' (Sekunden).
// perSide:     Vorgabe gilt pro Seite (bei Zeit: Timer läuft links, dann rechts).
// prog4:       ab Woche 3 ein vierter Satz (Sprung- und Kraftübungen).
// restSec:     feste Pause nach jedem Satz; sonst Standard je Phase (Hauptteil) bzw. keine (Warm-up/Cool-down).
// phaseNotes:  zusätzliche Hinweise ab Phase 2 (Woche 3–4) bzw. Phase 3 (Woche 5–6).
// yt:          Suchbegriff für YouTube.

const PLAN = {
  warmup: {
    title: 'Warm-up',
    duration: '8–10 Min.',
    items: [
      {
        id: 'jumping-jacks',
        name: 'Jumping Jacks & seitlicher Hampelmann',
        sets: 1, target: { kind: 'time', min: 60 },
        why: 'Bringt Kreislauf und Körpertemperatur hoch.',
        steps: [
          'Aufrechter Stand, Füße zusammen, Arme neben dem Körper.',
          'Springend die Beine grätschen und gleichzeitig die Arme über den Kopf führen.',
          'Zurückspringen in die Ausgangsposition – locker und rhythmisch.',
          'Nach ca. 30 Sek. wechseln: Arme nur seitlich bis Schulterhöhe führen (seitlicher Hampelmann).',
        ],
        cues: ['Auf den Fußballen landen, Knie leicht gebeugt.', 'Locker bleiben, Tempo langsam steigern.'],
        yt: 'jumping jacks richtig ausführen',
      },
      {
        id: 'worlds-greatest',
        name: "World's Greatest Stretch",
        sets: 1, perSide: true, target: { kind: 'reps', min: 4 },
        why: 'Mobilisiert Hüfte, Hüftbeuger, Brustwirbelsäule und Beinrückseite in einer Bewegung.',
        steps: [
          'Großer Ausfallschritt nach vorne, hinteres Bein möglichst gestreckt.',
          'Die innere Hand neben den vorderen Fuß setzen, den Ellenbogen Richtung Knöchel absenken.',
          'Den gleichen Arm nach oben aufdrehen, der Blick folgt der Hand.',
          'Hände neben den Fuß, Hüfte nach hinten schieben und das vordere Bein strecken (Dehnung hinten im Oberschenkel).',
          'Zurück in den Ausfallschritt, nächste Wiederholung; dann Seite wechseln.',
        ],
        cues: ['Langsam und kontrolliert, jede Position kurz halten.', 'In der Rotation ausatmen.'],
        yt: "world's greatest stretch",
      },
      {
        id: 'fire-hydrants',
        name: 'Hüftkreisen im Vierfüßlerstand (Fire Hydrants)',
        sets: 1, perSide: true, target: { kind: 'reps', min: 8 },
        why: 'Aktiviert die seitliche Gesäßmuskulatur und mobilisiert das Hüftgelenk.',
        steps: [
          'Vierfüßlerstand: Hände unter den Schultern, Knie unter der Hüfte.',
          'Ein Knie gebeugt seitlich anheben, bis der Oberschenkel etwa auf Hüfthöhe ist.',
          'Das Knie in einem großen Kreis nach vorne, zur Seite und nach hinten führen.',
          'Nach 8 Kreisen die Seite wechseln.',
        ],
        cues: ['Rücken bleibt gerade, das Becken kippt nicht zur Seite.', 'Die Bewegung kommt nur aus der Hüfte.'],
        yt: 'fire hydrant hip circles exercise',
      },
      {
        id: 'monster-walks',
        name: 'Monster Walks mit Mini-Band',
        sets: 2, target: { kind: 'reps', min: 10, unit: 'Schritte je Richtung' },
        why: 'Aktiviert die Hüftabduktoren und schult die Knieachse – wichtig für jede Landung.',
        steps: [
          'Mini-Band über die Knie legen, Füße hüftbreit, leichte Kniebeuge.',
          'Knie aktiv nach außen gegen das Band drücken.',
          '10 kleine Schritte diagonal vorwärts, dann 10 rückwärts.',
          'Danach 10 Schritte seitlich nach rechts und 10 nach links.',
        ],
        cues: ['Knie fallen nie nach innen.', 'Spannung im Band halten, Oberkörper ruhig.'],
        yt: 'monster walk mini band',
      },
      {
        id: 'glute-bridge',
        name: 'Glute Bridge mit Mini-Band',
        sets: 1, target: { kind: 'reps', min: 12 },
        why: 'Aktiviert den großen Gesäßmuskel als wichtigsten Motor für Sprung und Sprint.',
        steps: [
          'Rückenlage, Mini-Band über den Knien, Füße hüftbreit nah am Gesäß.',
          'Über die Fersen drücken und das Becken anheben, bis Knie, Hüfte und Schultern eine Linie bilden.',
          'Oben Gesäß anspannen, Knie gegen das Band nach außen drücken, 1 Sek. halten.',
          'Kontrolliert absenken.',
        ],
        cues: ['Kein Hohlkreuz – die Spannung kommt aus dem Gesäß, nicht aus dem Rücken.'],
        yt: 'glute bridge mini band',
      },
      {
        id: 'skippings',
        name: 'Skippings & Anfersen',
        sets: 2, setLabels: ['Skippings', 'Anfersen'], target: { kind: 'time', min: 20 },
        why: 'Aktiviert Hüftbeuger, Beinrückseite und Fußgelenke für schnelle Bewegungen.',
        steps: [
          'Skippings: schnelle, kurze Schritte auf der Stelle, Knie etwa bis Hüfthöhe, Arme arbeiten aktiv mit.',
          'Anfersen: schnelle Schritte auf der Stelle, die Fersen schwingen Richtung Gesäß.',
        ],
        cues: ['Immer auf den Fußballen bleiben.', 'Aufrechter Oberkörper, hohe Frequenz.'],
        yt: 'high knees butt kicks warm up',
      },
      {
        id: 'lateral-shuffle',
        name: 'Lateral Shuffle',
        sets: 3, target: { kind: 'time', min: 5 }, restSec: 20,
        why: 'Die handballtypische Abwehrbewegung – schnell und tief.',
        steps: [
          'Tiefe Abwehrposition: Füße breiter als schulterbreit, Knie gebeugt, Hüfte nach hinten, Arme vorne oben.',
          'So schnell wie möglich seitlich verschieben, ohne die Füße zu kreuzen oder zusammenzuschlagen.',
          'Bei wenig Platz nach 2–3 Schritten die Richtung wechseln.',
        ],
        cues: ['Tief bleiben, der Kopf bleibt auf gleicher Höhe.', 'Kurze, schnelle Bodenkontakte.'],
        yt: 'lateral shuffle defense drill',
      },
    ],
  },

  A: {
    title: 'Einheit A',
    subtitle: 'Schnelligkeit, Sprung & Landung',
    intro: 'Sprung- und Schnelligkeitsübungen zuerst ausführen, solange du frisch bist.',
    items: [
      {
        id: 'pogo-jumps',
        name: 'Pogo Jumps',
        sets: 3, target: { kind: 'time', min: 15 }, restSec: 45, prog4: true,
        why: 'Schnelle, kurze Sprünge aus dem Sprunggelenk – trainiert die Reaktivkraft von Waden und Achillessehne.',
        steps: [
          'Hüftbreiter Stand, Knie fast gestreckt, Gewicht auf den Fußballen.',
          'Schnell und federnd hüpfen – die Bewegung kommt fast nur aus dem Sprunggelenk.',
          'Bodenkontakt so kurz wie möglich halten, die Fersen berühren den Boden nicht.',
          'Arme locker mitschwingen lassen.',
        ],
        cues: ['Stell dir vor, der Boden ist heiß.', 'Rumpf fest, möglichst leise landen.', 'Lieber etwas niedriger, dafür schneller.'],
        phaseNotes: { 3: 'Über ein kleines Hindernis (z. B. zusammengerolltes Handtuch) vor und zurück springen.' },
        yt: 'pogo jumps ankle hops technique',
      },
      {
        id: 'skater-jumps',
        name: 'Skater Jumps mit Stand-Landung',
        sets: 3, perSide: true, target: { kind: 'reps', min: 5 }, prog4: true,
        why: 'Seitlicher Absprung mit einbeiniger Landung – schult Kraft und Landekontrolle für Richtungswechsel.',
        steps: [
          'Auf einem Bein stehen, Knie leicht gebeugt, Oberkörper leicht nach vorne.',
          'Kraftvoll seitlich abspringen und auf dem anderen Bein landen.',
          'Die Landung 2 Sek. stabil halten („einfrieren“), dann zurückspringen.',
        ],
        cues: ['Knie über dem Fuß – nicht nach innen fallen lassen.', 'Hüfte bei der Landung nach hinten, leise landen.', 'Erst Stabilität, dann Weite.'],
        phaseNotes: { 3: 'Seitlich über ein kleines Hindernis springen.' },
        yt: 'skater jump stick landing',
      },
      {
        id: 'drop-stick',
        name: 'Drop & Stick',
        sets: 3, target: { kind: 'reps', min: 6 }, prog4: true,
        why: 'Schnelles Abbremsen in die tiefe Abwehrposition – trainiert die exzentrische Kraft und stabile Knieachse.',
        steps: [
          'Aufrechter Stand, auf die Zehenspitzen gehen, Arme nach oben strecken.',
          'Explosiv „fallen lassen“: Füße schnell etwas breiter als schulterbreit setzen und in die tiefe Abwehrposition gehen.',
          'Die Position abrupt abfangen und 2 Sek. einfrieren.',
          'Aufrichten, nächste Wiederholung.',
        ],
        cues: ['Hüfte nach hinten, Knie über den Fußspitzen.', 'Gewicht auf dem ganzen Fuß, Rücken gerade.', 'Keine Nachbewegung nach der Landung.'],
        yt: 'snap down drill athletic stance',
      },
      {
        id: 'jumpshot-landing',
        name: 'Sprungwurf-Landung einbeinig',
        sets: 3, perSide: true, target: { kind: 'reps', min: 4 }, prog4: true,
        why: 'Simuliert den Sprungwurf – die einbeinige Landung ist eine der häufigsten Verletzungssituationen im Handball.',
        steps: [
          'Aus einem kurzen Anlaufschritt nach oben abspringen.',
          'In der Luft eine Wurfbewegung mit dem Arm ausführen (ausholen und durchziehen).',
          'Auf dem Bein gegenüber dem Wurfarm landen (Rechtshänder: links).',
          'Die Landung 3 Sek. stabil halten. „Pro Seite“ heißt: auch mit dem anderen Arm und Bein.',
        ],
        cues: ['Weich landen: Ballen, dann Ferse, Knie und Hüfte beugen.', 'Knie über dem Fuß, die Hüfte knickt nicht seitlich weg.'],
        phaseNotes: { 3: 'Über ein kleines Hindernis abspringen und höher springen.' },
        yt: 'handball jump shot landing single leg',
      },
      {
        id: 'reaction-shuffle',
        name: 'Reaktions-Shuffle',
        sets: 4, target: { kind: 'time', min: 5, unit: 'Durchgang' }, restSec: 30, reaction: true,
        why: 'Reagieren auf Kommandos wie in der Abwehr. Die App gibt dir die Richtung vor (Anzeige + Sprachausgabe).',
        steps: [
          'Tiefe Abwehrposition einnehmen, Blick aufs Handy.',
          'Timer starten: Die App zeigt und sagt „Links“, „Rechts“ oder „Vor“.',
          'Links/Rechts: schnell 1–2 Shuffle-Schritte in die Richtung. Vor: 1–2 Schritte heraustreten, dann zurück.',
          '5 Sek. volle Belastung, danach Pause.',
        ],
        cues: ['Tief bleiben, nicht aufrichten.', 'Füße nicht kreuzen.', 'So schnell wie möglich reagieren.'],
        yt: 'reactive lateral shuffle drill',
      },
      {
        id: 'nordic',
        name: 'Nordic Hamstring Curls',
        sets: 3, target: { kind: 'reps', min: 4, max: 6 }, prog4: true,
        why: 'Beugt nachweislich Oberschenkelzerrungen vor – eine der wirksamsten Präventionsübungen überhaupt.',
        steps: [
          'Auf eine Matte knien, die Fersen unter dem Sofa (oder Bett) fixieren.',
          'Körper gestreckt: Knie, Hüfte und Schultern bilden eine Linie, Gesäß anspannen.',
          'Langsam nach vorne ablassen und mit der Oberschenkelrückseite so lange wie möglich bremsen.',
          'Wenn es nicht mehr geht, mit den Händen abfangen (Liegestützposition).',
          'Mit den Händen leicht abdrücken und zurück in die Startposition kommen.',
        ],
        cues: ['Die Hüfte bleibt gestreckt – nicht abknicken.', 'Langsam! Das Absenken ist die eigentliche Übung.', 'Prüfe, ob das Sofa sicher steht und nicht kippt.'],
        phaseNotes: { 3: 'Noch langsamer absenken (5 Sek. und mehr).' },
        yt: 'nordic hamstring curl at home couch',
      },
      {
        id: 'copenhagen',
        name: 'Copenhagen Plank',
        sets: 3, perSide: true, target: { kind: 'time', min: 15, max: 20 },
        why: 'Seitstütz mit dem oberen Bein auf dem Sofa – schützt Leiste und Adduktoren.',
        steps: [
          'Seitlage neben dem Sofa, Unterarm am Boden, Ellenbogen unter der Schulter.',
          'Das obere Bein auf das Sofa legen. Einsteiger: Knie auflegen. Fortgeschritten: Bein gestreckt, Knöchel auflegen.',
          'Das untere Bein hängt frei unter dem Sofa.',
          'Hüfte anheben, bis der Körper eine gerade Linie bildet, und halten.',
        ],
        cues: ['Hüfte nicht absacken lassen.', 'Becken nicht nach hinten aufdrehen.', 'Ruhig weiteratmen.'],
        phaseNotes: { 2: 'Bein jetzt gestreckt auflegen (Knöchel auf dem Sofa).' },
        yt: 'copenhagen plank beginner',
      },
      {
        id: 'pallof',
        name: 'Pallof Press mit Band',
        sets: 3, perSide: true, target: { kind: 'reps', min: 10 },
        why: 'Anti-Rotation: Der Rumpf widersteht dem Zug des Bandes – Grundlage für stabile Würfe und Zweikämpfe.',
        steps: [
          'Band seitlich auf Brusthöhe fixieren (z. B. Türanker, Tischbein).',
          'Seitlich zum Anker stehen, Füße schulterbreit, Knie leicht gebeugt, Band vor dem Brustbein halten.',
          'Arme langsam gerade nach vorne drücken, 1–2 Sek. halten.',
          'Kontrolliert zurück zur Brust. Danach andersherum hinstellen.',
        ],
        cues: ['Schultern und Hüfte zeigen immer nach vorne – nicht verdrehen lassen.', 'Beim Drücken ausatmen, Bauch fest.'],
        phaseNotes: { 2: 'Stärkeres Band verwenden oder weiter vom Anker weggehen.' },
        yt: 'pallof press resistance band',
      },
    ],
  },

  B: {
    title: 'Einheit B',
    subtitle: 'Kraft, Stabilität & Rotation',
    intro: 'Langsam und kontrolliert arbeiten – saubere Technik vor Gewicht und Tempo.',
    items: [
      {
        id: 'bulgarian',
        name: 'Bulgarian Split Squat',
        sets: 3, perSide: true, target: { kind: 'reps', min: 8, max: 10 }, prog4: true,
        why: 'Einbeinige Kraft für Sprung, Antritt und Landung.',
        steps: [
          'Mit dem Rücken zum Sofa stehen, den hinteren Fußrücken auf das Sofa legen.',
          'Der vordere Fuß steht etwa einen großen Schritt vor dem Sofa.',
          'Senkrecht absenken, bis der vordere Oberschenkel etwa parallel zum Boden ist.',
          'Über die Ferse des vorderen Fußes wieder hochdrücken.',
          'Optional: Band unter den vorderen Fuß legen und die Enden auf Schulterhöhe halten.',
        ],
        cues: ['Das vordere Knie zeigt über den 2.–3. Zeh, nicht nach innen.', 'Leichte Vorlage des Oberkörpers ist okay.'],
        phaseNotes: { 2: 'Mit Band als Widerstand bzw. stärkerem Band.' },
        yt: 'bulgarian split squat couch at home',
      },
      {
        id: 'sl-rdl',
        name: 'Einbeiniges Kreuzheben (Single Leg RDL) mit Band',
        sets: 3, perSide: true, target: { kind: 'reps', min: 8 }, prog4: true,
        why: 'Trainiert Gleichgewicht und Oberschenkelrückseite (Hamstrings).',
        steps: [
          'Band unter den Standfuß legen, die Enden in beide Hände nehmen.',
          'Standbein leicht gebeugt, Hüfte nach hinten schieben und den Oberkörper nach vorne kippen.',
          'Das freie Bein streckt sich dabei nach hinten – Oberkörper und Bein bilden eine Linie.',
          'Absenken, bis du deutlich die Rückseite des Standbeins spürst (ca. 3 Sek.).',
          'Über das Gesäß wieder aufrichten.',
        ],
        cues: ['Rücken bleibt gerade.', 'Die Hüfte bleibt parallel zum Boden – nicht aufdrehen.', 'Langsam, besonders nach unten.'],
        phaseNotes: { 2: 'Stärkeres Band verwenden.' },
        yt: 'single leg rdl resistance band',
      },
      {
        id: 'lateral-lunge',
        name: 'Lateral Lunge (Seitausfallschritt)',
        sets: 3, perSide: true, target: { kind: 'reps', min: 8 }, prog4: true,
        why: 'Verbessert Adduktoren-Beweglichkeit und die Kraft für den Seitwärtsschritt.',
        steps: [
          'Breiter Stand, Füße zeigen nach vorne.',
          'Das Gewicht auf eine Seite verlagern: Hüfte nach hinten, Knie beugen.',
          'Das andere Bein bleibt gestreckt – Dehnung an der Innenseite.',
          'Kräftig über das gebeugte Bein zurück in die Mitte drücken.',
        ],
        cues: ['Ferse des gebeugten Beins bleibt am Boden.', 'Knie über dem Fuß, Brust aufrecht.'],
        yt: 'lateral lunge proper form',
      },
      {
        id: 'band-walk',
        name: 'Seitlicher Band-Walk in tiefer Abwehrposition',
        sets: 3, target: { kind: 'reps', min: 12, unit: 'Schritte je Richtung' },
        why: 'Kräftigt die seitliche Hüfte in der handballtypischen Abwehrhaltung.',
        steps: [
          'Mini-Band über den Knien (schwerer: um die Knöchel).',
          'In die tiefe Abwehrposition gehen: Hüfte nach hinten, Knie gebeugt, Arme vorne.',
          '12 Seitschritte nach rechts, dann 12 nach links – ohne hochzukommen.',
        ],
        cues: ['Spannung im Band halten, die Füße kommen nie ganz zusammen.', 'Oberkörper bleibt auf gleicher Höhe.'],
        phaseNotes: { 2: 'Stärkeres Band oder Band um die Knöchel.' },
        yt: 'banded lateral walk athletic stance',
      },
      {
        id: 'calf-raise',
        name: 'Einbeinige Wadenheber',
        sets: 3, perSide: true, target: { kind: 'reps', min: 12, max: 15 }, prog4: true,
        why: 'Schützen Sprunggelenk und Achillessehne.',
        steps: [
          'Auf einem Bein stehen, gern mit dem Fußballen auf einer Treppenstufe; an der Wand festhalten.',
          'Ferse langsam absenken (bei der Stufe unter Stufenhöhe).',
          'So hoch wie möglich auf den Fußballen drücken und oben 2 Sek. halten.',
          'Langsam (2–3 Sek.) wieder absenken.',
        ],
        cues: ['Knie fast gestreckt.', 'Volle Bewegungsamplitude, nicht wippen.'],
        yt: 'single leg calf raise step',
      },
      {
        id: 'wood-chopper',
        name: 'Wood Chopper mit Band',
        sets: 3, perSide: true, target: { kind: 'reps', min: 10 },
        why: 'Diagonale Rotation von oben nach unten – entspricht der Wurfbewegung.',
        steps: [
          'Band seitlich hoch fixieren (z. B. Türanker oben in der Tür).',
          'Seitlich zum Anker stehen, das Band mit beiden Händen über der Schulter greifen.',
          'Diagonal nach unten zur gegenüberliegenden Hüfte ziehen, dabei aus Hüfte und Rumpf rotieren.',
          'Kontrolliert zurück in die Ausgangsposition.',
        ],
        cues: ['Zügig nach unten, langsam zurück.', 'Die Hüfte dreht mit wie beim Wurf, der hintere Fuß dreht auf dem Ballen.', 'Arme bleiben relativ gestreckt.'],
        phaseNotes: { 2: 'Stärkeres Band verwenden.' },
        yt: 'resistance band wood chopper high to low',
      },
      {
        id: 'side-plank-abd',
        name: 'Seitstütz mit Beinabspreizen',
        sets: 3, perSide: true, target: { kind: 'reps', min: 8 },
        why: 'Kräftigt seitliche Rumpfmuskulatur und Hüftabduktoren gleichzeitig.',
        steps: [
          'Seitstütz auf dem Unterarm, Ellenbogen unter der Schulter, Beine gestreckt (leichter: unteres Knie am Boden).',
          'Hüfte anheben, bis der Körper eine gerade Linie bildet.',
          'Das obere Bein gestreckt ca. 30–45° anheben, Fußspitze zeigt nach vorne.',
          'Langsam absenken, ohne dass die Hüfte absackt.',
        ],
        cues: ['Hüfte bleibt oben.', 'Bein nicht nach vorne ziehen, sondern gerade zur Seite.'],
        yt: 'side plank hip abduction',
      },
      {
        id: 'dead-bug',
        name: 'Dead Bug',
        sets: 3, perSide: true, target: { kind: 'reps', min: 8 },
        why: 'Rumpfstabilität bei gleichzeitiger Arm- und Beinbewegung.',
        steps: [
          'Rückenlage, Arme senkrecht nach oben, Hüfte und Knie 90° gebeugt.',
          'Den unteren Rücken aktiv in den Boden drücken.',
          'Gegengleich einen Arm über den Kopf und das andere Bein nach vorne strecken – knapp über dem Boden.',
          'Zurück zur Mitte, dann die andere Seite.',
        ],
        cues: ['Die Lendenwirbelsäule bleibt die ganze Zeit am Boden.', 'Hebt der Rücken ab: Bewegung kleiner machen.', 'Beim Strecken ausatmen.'],
        yt: 'dead bug exercise proper form',
      },
    ],
  },

  cooldown: {
    title: 'Cool-down & Beweglichkeit',
    duration: '5–7 Min.',
    items: [
      {
        id: 'hip-flexor',
        name: 'Hüftbeuger-Dehnung im Halbkniestand',
        sets: 1, perSide: true, target: { kind: 'time', min: 45 },
        why: 'Löst den Hüftbeuger, der durch Sitzen und Sprints oft verkürzt ist.',
        steps: [
          'Halbkniestand: ein Knie auf der Matte, das andere Bein vorne im 90°-Winkel.',
          'Becken aufrichten (Gesäß der Knieseite anspannen).',
          'Die Hüfte langsam nach vorne schieben, bis du vorne in der Leiste eine Dehnung spürst.',
          'Optional den Arm der Knieseite nach oben strecken und leicht zur Gegenseite neigen.',
        ],
        cues: ['Kein Hohlkreuz.', 'Ruhig atmen, nicht wippen.'],
        yt: 'half kneeling hip flexor stretch',
      },
      {
        id: 'ninety-ninety',
        name: '90/90-Hüftrotation',
        sets: 1, target: { kind: 'reps', min: 8, unit: 'Seitenwechsel' },
        why: 'Verbessert Innen- und Außenrotation der Hüfte.',
        steps: [
          'Auf dem Boden sitzen, beide Beine 90° gebeugt: ein Bein vor dem Körper, eines seitlich hinter dir.',
          'Aufrecht sitzen, bei Bedarf mit den Händen hinten abstützen.',
          'Die Knie anheben und beide Beine wie Scheibenwischer auf die andere Seite drehen.',
        ],
        cues: ['Oberkörper aufrecht.', 'Langsam und ohne Schwung.'],
        yt: '90 90 hip switch mobility',
      },
      {
        id: 'adductor-rock',
        name: 'Adductor Rock Backs',
        sets: 1, perSide: true, target: { kind: 'reps', min: 10 },
        why: 'Mobilisiert die Adduktoren (Innenseite Oberschenkel).',
        steps: [
          'Vierfüßlerstand, ein Bein gestreckt zur Seite ausstrecken, Fuß flach am Boden.',
          'Das Gesäß langsam nach hinten Richtung Ferse schieben, bis du innen eine Dehnung spürst.',
          'Zurück nach vorne.',
        ],
        cues: ['Rücken bleibt gerade.', 'Die Fußspitze des gestreckten Beins zeigt nach vorne.'],
        yt: 'adductor rock back',
      },
      {
        id: 'knee-to-wall',
        name: 'Knee-to-Wall',
        sets: 1, perSide: true, target: { kind: 'reps', min: 10 },
        why: 'Verbessert die Beweglichkeit im Sprunggelenk – wichtig für saubere Landungen.',
        steps: [
          'Schrittstellung vor einer Wand, der vordere Fuß ca. 8–12 cm von der Wand entfernt.',
          'Das vordere Knie über den 2.–3. Zeh Richtung Wand schieben.',
          'Die Ferse bleibt am Boden. Kurz halten, zurück.',
        ],
        cues: ['Wird es zu leicht: Fuß etwas weiter weg von der Wand.'],
        yt: 'knee to wall ankle mobility',
      },
      {
        id: 'childs-pose',
        name: 'Kindhaltung mit tiefer Atmung',
        sets: 1, target: { kind: 'time', min: 60 },
        why: 'Entspannt Rücken und Hüfte und bringt den Puls herunter.',
        steps: [
          'Knie etwas auseinander, Gesäß Richtung Fersen.',
          'Arme nach vorne ausstrecken, Stirn ablegen.',
          'Tief in Bauch und Rücken atmen: 4 Sek. ein, 6 Sek. aus.',
        ],
        cues: ['Schultern loslassen.'],
        yt: 'childs pose breathing',
      },
    ],
  },
};

const PHASES = {
  1: {
    title: 'Woche 1–2: Technik lernen',
    points: ['Technik sauber lernen', 'Jeweils die untere Wiederholungszahl', '60–90 Sek. Pause'],
    rest: 75, restLabel: '60–90 Sek.',
  },
  2: {
    title: 'Woche 3–4: Umfang steigern',
    points: ['4 Sätze bei Sprung- und Kraftübungen', 'Stärkeres Band', 'Copenhagen Plank mit gestrecktem Bein'],
    rest: 75, restLabel: '60–90 Sek.',
  },
  3: {
    title: 'Woche 5–6: Intensität steigern',
    points: ['Pausen auf 45–60 Sek. verkürzen', 'Sprünge über ein Hindernis', 'Nordics langsamer absenken'],
    rest: 50, restLabel: '45–60 Sek.',
  },
};

const SAFETY = [
  'Qualität vor Tempo – besonders bei den Landungen.',
  'Das Knie darf nicht nach innen fallen.',
  'Stechende Schmerzen: sofort aufhören.',
  'Spiel am Wochenende: letzte Einheit spätestens 2 Tage vorher.',
];
